window.GOALTASK_TEAM_CATALOG = [
  // Campeonato Brasileiro Série A 2026 — CBF
  ['cap', 'Athletico Paranaense', 'Campeonato Brasileiro Série A', '⚽', ['Athletico-PR']],
  ['cam', 'Atlético Mineiro', 'Campeonato Brasileiro Série A', '⚽', ['Atlético-MG']],
  ['bah', 'Bahia', 'Campeonato Brasileiro Série A', '⚽', []],
  ['bot', 'Botafogo', 'Campeonato Brasileiro Série A', '⚽', ['Botafogo-RJ']],
  ['cha', 'Chapecoense', 'Campeonato Brasileiro Série A', '⚽', []],
  ['cor', 'Corinthians', 'Campeonato Brasileiro Série A', '⚽', []],
  ['cfc', 'Coritiba', 'Campeonato Brasileiro Série A', '⚽', ['Coritiba SAF']],
  ['cru', 'Cruzeiro', 'Campeonato Brasileiro Série A', '⚽', []],
  ['fla', 'Flamengo', 'Campeonato Brasileiro Série A', '⚽', []],
  ['flu', 'Fluminense', 'Campeonato Brasileiro Série A', '⚽', []],
  ['gre', 'Grêmio', 'Campeonato Brasileiro Série A', '⚽', ['Gremio']],
  ['int', 'Internacional', 'Campeonato Brasileiro Série A', '⚽', []],
  ['mir', 'Mirassol', 'Campeonato Brasileiro Série A', '⚽', []],
  ['pal', 'Palmeiras', 'Campeonato Brasileiro Série A', '⚽', []],
  ['rbb', 'Red Bull Bragantino', 'Campeonato Brasileiro Série A', '⚽', ['Bragantino']],
  ['rem', 'Remo', 'Campeonato Brasileiro Série A', '⚽', []],
  ['san', 'Santos', 'Campeonato Brasileiro Série A', '⚽', ['Santos FC']],
  ['sao', 'São Paulo', 'Campeonato Brasileiro Série A', '⚽', ['São Paulo FC', 'Sao Paulo']],
  ['vas', 'Vasco da Gama', 'Campeonato Brasileiro Série A', '⚽', ['Vasco', 'Vasco da Gama SAF']],
  ['vit', 'Vitória', 'Campeonato Brasileiro Série A', '⚽', ['Vitoria']],

  // 48 seleções da Copa do Mundo FIFA 2026 — FIFA
  ['arg', 'Argentina', 'Copa do Mundo FIFA 2026', '🇦🇷', []],
  ['alg', 'Argélia', 'Copa do Mundo FIFA 2026', '🇩🇿', ['Algeria']],
  ['aus', 'Austrália', 'Copa do Mundo FIFA 2026', '🇦🇺', ['Australia']],
  ['aut', 'Áustria', 'Copa do Mundo FIFA 2026', '🇦🇹', ['Austria']],
  ['bel', 'Bélgica', 'Copa do Mundo FIFA 2026', '🇧🇪', ['Belgium']],
  ['bih', 'Bósnia e Herzegovina', 'Copa do Mundo FIFA 2026', '🇧🇦', ['Bosnia and Herzegovina']],
  ['bra', 'Brasil', 'Copa do Mundo FIFA 2026', '🇧🇷', ['Brazil']],
  ['can', 'Canadá', 'Copa do Mundo FIFA 2026', '🇨🇦', ['Canada']],
  ['cpv', 'Cabo Verde', 'Copa do Mundo FIFA 2026', '🇨🇻', []],
  ['col', 'Colômbia', 'Copa do Mundo FIFA 2026', '🇨🇴', ['Colombia']],
  ['kor', 'Coreia do Sul', 'Copa do Mundo FIFA 2026', '🇰🇷', ['Korea Republic', 'South Korea']],
  ['civ', 'Costa do Marfim', 'Copa do Mundo FIFA 2026', '🇨🇮', ["Côte d'Ivoire", 'Ivory Coast']],
  ['cro', 'Croácia', 'Copa do Mundo FIFA 2026', '🇭🇷', ['Croatia']],
  ['cuw', 'Curaçao', 'Copa do Mundo FIFA 2026', '🇨🇼', ['Curacao']],
  ['ecu', 'Equador', 'Copa do Mundo FIFA 2026', '🇪🇨', ['Ecuador']],
  ['egy', 'Egito', 'Copa do Mundo FIFA 2026', '🇪🇬', ['Egypt']],
  ['sco', 'Escócia', 'Copa do Mundo FIFA 2026', '🏴', ['Scotland']],
  ['esp', 'Espanha', 'Copa do Mundo FIFA 2026', '🇪🇸', ['Spain']],
  ['usa', 'Estados Unidos', 'Copa do Mundo FIFA 2026', '🇺🇸', ['USA', 'United States']],
  ['fra', 'França', 'Copa do Mundo FIFA 2026', '🇫🇷', ['France']],
  ['gha', 'Gana', 'Copa do Mundo FIFA 2026', '🇬🇭', ['Ghana']],
  ['hai', 'Haiti', 'Copa do Mundo FIFA 2026', '🇭🇹', []],
  ['ned', 'Países Baixos', 'Copa do Mundo FIFA 2026', '🇳🇱', ['Netherlands', 'Holanda']],
  ['eng', 'Inglaterra', 'Copa do Mundo FIFA 2026', '🏴', ['England']],
  ['irn', 'Irã', 'Copa do Mundo FIFA 2026', '🇮🇷', ['IR Iran', 'Iran']],
  ['irq', 'Iraque', 'Copa do Mundo FIFA 2026', '🇮🇶', ['Iraq']],
  ['jpn', 'Japão', 'Copa do Mundo FIFA 2026', '🇯🇵', ['Japan']],
  ['jor', 'Jordânia', 'Copa do Mundo FIFA 2026', '🇯🇴', ['Jordan']],
  ['mar', 'Marrocos', 'Copa do Mundo FIFA 2026', '🇲🇦', ['Morocco']],
  ['mex', 'México', 'Copa do Mundo FIFA 2026', '🇲🇽', ['Mexico']],
  ['nzl', 'Nova Zelândia', 'Copa do Mundo FIFA 2026', '🇳🇿', ['New Zealand']],
  ['nor', 'Noruega', 'Copa do Mundo FIFA 2026', '🇳🇴', ['Norway']],
  ['pan', 'Panamá', 'Copa do Mundo FIFA 2026', '🇵🇦', ['Panama']],
  ['par', 'Paraguai', 'Copa do Mundo FIFA 2026', '🇵🇾', ['Paraguay']],
  ['por', 'Portugal', 'Copa do Mundo FIFA 2026', '🇵🇹', []],
  ['qat', 'Catar', 'Copa do Mundo FIFA 2026', '🇶🇦', ['Qatar']],
  ['cod', 'RD Congo', 'Copa do Mundo FIFA 2026', '🇨🇩', ['Congo DR', 'DR Congo']],
  ['cze', 'República Tcheca', 'Copa do Mundo FIFA 2026', '🇨🇿', ['Czechia', 'Czech Republic']],
  ['ksa', 'Arábia Saudita', 'Copa do Mundo FIFA 2026', '🇸🇦', ['Saudi Arabia']],
  ['sen', 'Senegal', 'Copa do Mundo FIFA 2026', '🇸🇳', []],
  ['rsa', 'África do Sul', 'Copa do Mundo FIFA 2026', '🇿🇦', ['South Africa']],
  ['swe', 'Suécia', 'Copa do Mundo FIFA 2026', '🇸🇪', ['Sweden']],
  ['sui', 'Suíça', 'Copa do Mundo FIFA 2026', '🇨🇭', ['Switzerland']],
  ['tun', 'Tunísia', 'Copa do Mundo FIFA 2026', '🇹🇳', ['Tunisia']],
  ['tur', 'Turquia', 'Copa do Mundo FIFA 2026', '🇹🇷', ['Türkiye', 'Turkey']],
  ['uru', 'Uruguai', 'Copa do Mundo FIFA 2026', '🇺🇾', ['Uruguay']],
  ['uzb', 'Uzbequistão', 'Copa do Mundo FIFA 2026', '🇺🇿', ['Uzbekistan']],
  ['ger', 'Alemanha', 'Copa do Mundo FIFA 2026', '🇩🇪', ['Germany']],
].map(([code, name, competition, badge, aliases]) => ({
  code,
  name,
  competition,
  badge,
  aliases,
  logo: competition.includes('Copa do Mundo') ? `assets/flags/${code}.png` : `assets/teams/${code}.png`,
}));
